- hosts: all
  become: yes
  become_user: root
  vars:
    database_name: FireGolem
    database_backup: /tmp/FireGolem-{{ansible_date_time.iso8601_basic_short}}.sql

  tasks:

  - name: Dump database
    mysql_db: name={{database_name}} state=dump target={{database_backup}}

  - name: Compress DB backup
    archive: path={{database_backup}} dest={{database_backup}}.gz format=gz remove=yes

  - name: Fetch DB backup.
    fetch: src={{database_backup}}.gz dest="~/Google Drive/Backups/DBs/" flat=yes fail_on_missing=yes validate_checksum=yes
